### ISSUE TITLE
Dies pretty quickly in some project directories

### ISSUE THREAD

**Issue by joeygibson** [isacikgoz/gitin#6]
I'm on a Macbook Pro, Mojave, 10.14.2 (18C54).

In some git projects, running `gitin log`, or even `git -h`, results in an error

> could not find repository from '/Users/myusername/Projects/myproject'

Any other git tool (like `tig`) works fine. It's not _all_ projects, just some, which is odd. 

I've narrowed it down to line 61, in `gopkg.in/libgit2/git2go.v27/repository.go`, which is this call into C code 

```
ret := C.git_repository_open(&ptr, cpath)
```

This happened with both the release download, and with a version I built following the build instructions.

If I can provide any more info, please let me know.

**Comment by isacikgoz** [comment]
Thanks for the comprehensive report @joeygibson 

I need further information of those repositories and I suspect if they are shallow clones. Because there are some issues I also experienced with shallow clones.

The `gitin -h`fail is a bug that I never experienced. I also tested it outside a git repository and got the same error, which is inappropriate to be like that. I will fix that first.

**Comment by joeygibson** [comment]
The first repo that it was failing on was not a clone. It was a repo I'd created locally using `git init`, and subsequently pushed to github.

**Comment by jrobichaud** [comment]
Easy to reproduce for me.

Example: 
`/somepath` is a git directory

```bash
$ cd /somepath/subdirectory
$ gitin status
could not find repository from '/somepath/subdirectory'
```

Using `gitin version 0.1.0`

**Comment by isacikgoz** [comment]
I've just fixed it and it's merged to master. Please let me know if you still the issue. Also, feel free to open a new issue.

**Comment by joeygibson** [comment]
I just installed v1.0.2 and it works.
